#!/usr/bin/env node
// Best GEO CLI text-to-image wrapper. No platform credential is read by this script.
const fs=require('fs'),path=require('path');
const {call,plan,apply}=require('../../geo-runtime/scripts/best_geo.js');
function argsOf(){const o={};for(let i=2;i<process.argv.length;i++){const t=process.argv[i];if(!t.startsWith('--'))continue;const k=t.slice(2);const n=process.argv[i+1];if(!n||n.startsWith('--'))o[k]=true;else{o[k]=n;i++}}return o}
function first(a,ks,d){for(const k of ks)if(a[k]!==undefined&&a[k]!==true)return a[k];return d}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function download(url,file){const r=await fetch(url);if(!r.ok)throw Error(`下载图片失败 HTTP ${r.status}`);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,Buffer.from(await r.arrayBuffer()));return file}
(async()=>{const a=argsOf();const prompt=String(first(a,['prompt'],'')).trim();const productId=Number(first(a,['product-id','productId'],0));if(!prompt||!productId)throw Error('需要 --prompt 和 --product-id');const input={prompt,productId,negativePrompt:first(a,['negative-prompt','negativePrompt'],undefined),aspectRatio:first(a,['aspect-ratio','aspectRatio'],'1:1'),model:first(a,['model'],undefined)};Object.keys(input).forEach(k=>input[k]===undefined&&delete input[k]);if(a['dry-run']){console.log(JSON.stringify({dryRun:true,capability:'textToImages.create',input},null,2));return}if(!a.force)throw Error('创建文生图任务前请先 --dry-run；确认后使用 --force。');const p=await plan('textToImages.create',input);const pid=p?.data?.planId||p?.planId;if(!pid)throw Error('CLI 未返回 planId');const created=await apply(pid);let id=Number(created?.data?.id||created?.data?.taskId||created?.id||0),detail=created;const wait=a.wait!==false&&!a['no-wait'];if(wait&&id){const timeout=Number(first(a,['timeout-ms'],300000)),start=Date.now();while(Date.now()-start<timeout){detail=await call('textToImages.get',{id});const d=detail?.data||detail;const status=Number(d?.status||0);if(status===3||status===4)break;await sleep(Math.min(10000,Number(first(a,['interval-ms'],3000))))}}const d=detail?.data||detail;const urls=d?.resourceUrls||created?.data?.resourceUrls||[];let output=first(a,['output'],undefined);if(output&&urls[0])output=await download(urls[0],path.resolve(output));const result={created:created?.data||created,taskId:id,detail:d,resourceUrls:urls,output};const jsonOut=first(a,['json-out','jsonOut'],undefined);if(jsonOut){fs.mkdirSync(path.dirname(path.resolve(jsonOut)),{recursive:true});fs.writeFileSync(path.resolve(jsonOut),JSON.stringify(result,null,2)+'\n')}console.log(JSON.stringify(result,null,2));})().catch(e=>{console.error(e.message||e);process.exit(1)});
