#!/usr/bin/env node
/** GEO keyword pool and state machine helper. */
const fs = require('fs');
const path = require('path');
const { unwrapRows } = require('../../geo-runtime/scripts/json_helpers.js');

const FIELDS = ['keyword','question','priority','status','commercial_value','brand_presence','competitor_risk','source_gap','content_status','published_url','exact_url_hit','weak_hit','last_evidence','source','next_action','notes','created_at','updated_at'];
const STATES = new Set(['planned','baseline_done','need_content','published','postpublish_monitoring','source_gap','stable','regression','blocked']);
function parseArgs(argv){const out={_:[]};for(let i=2;i<argv.length;i++){const t=argv[i];if(!t.startsWith('--')){out._.push(t);continue;}const raw=t.slice(2);if(raw.startsWith('no-')){out[raw.slice(3)]=false;continue;}const eq=raw.indexOf('=');if(eq>=0){out[raw.slice(0,eq)]=raw.slice(eq+1);continue;}const n=argv[i+1];if(!n||n.startsWith('--'))out[raw]=true;else{out[raw]=n;i++;}}return out;}
function first(args,names,fb=undefined){for(const n of names)if(args[n]!==undefined&&args[n]!=='')return args[n];return fb;}
function splitList(v){return String(v||'').split(/[,，\n|]/).map(s=>s.trim()).filter(Boolean);}
function now(){return new Date().toISOString();}
function today(){return new Date().toISOString().slice(0,10);}
function ensureDir(d){fs.mkdirSync(d,{recursive:true});return d;}
function outDir(args){const explicit=first(args,['output-dir','outputDir']);if(explicit)return path.resolve(String(explicit));const projectDir=path.resolve(String(first(args,['project-dir','projectDir'],'.')));return path.join(projectDir,'03_规划方案','关键词池');}
function usage(){console.log(`Usage:
  node geo-keyword-pool/scripts/keyword_pool.js --action init --project-dir 项目_示例品牌GEO
  node geo-keyword-pool/scripts/keyword_pool.js --action import --file questions.md --project-dir 项目_示例品牌GEO
  node geo-keyword-pool/scripts/keyword_pool.js --action import-answers --answers-json answers.json --brand 示例品牌A
  node geo-keyword-pool/scripts/keyword_pool.js --action next --project-dir 项目_示例品牌GEO --top 20
Actions: init, import, import-answers, update, next, summary
`);}
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}
function parseCsvLine(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++;}else q=!q;}else if(ch===','&&!q){out.push(cur);cur='';}else cur+=ch;}out.push(cur);return out;}
function parseCsv(text){const lines=String(text||'').split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const h=parseCsvLine(lines[0]);return lines.slice(1).map(l=>{const c=parseCsvLine(l);const r={};h.forEach((x,i)=>r[x]=c[i]||'');return r;});}
function writeCsv(file,rows){fs.writeFileSync(file,[FIELDS.join(','),...rows.map(r=>FIELDS.map(f=>csvEscape(r[f])).join(','))].join('\n')+'\n','utf8');}
function poolFile(dir){return path.join(dir,'keyword_pool.csv');}
function loadPool(dir){const f=poolFile(dir);return fs.existsSync(f)?parseCsv(fs.readFileSync(f,'utf8')):[];}
function normalizeQuestion(s){return String(s||'').replace(/^\s*[-*+\d.、)]+\s*/,'').replace(/\s+/g,' ').trim();}
function keywordOf(q){return normalizeQuestion(q).replace(/[？?。！!].*$/,'').slice(0,60);}
function readQuestions(file){const text=fs.readFileSync(path.resolve(file),'utf8').replace(/^---[\s\S]*?---\s*/,'');const ext=path.extname(file).toLowerCase();if(ext==='.json')return unwrapRows(JSON.parse(text)).map(x=>typeof x==='string'?x:(x.question||x.topic||x.keyword||x.title||'')).filter(Boolean);if(ext==='.csv'){const rows=parseCsv(text);return rows.map(r=>r.question||r.topic||r.keyword||r['问题']||r['关键词']||Object.values(r)[0]).filter(Boolean);}return text.split(/\r?\n/).map(normalizeQuestion).filter(x=>x&&!/^#|^```|^\|?[-: ]+\|?$/.test(x));}
function scorePriority(row){let score=0;if(/高|强|成交|价格|服务商|推荐|榜单|哪家|费用|报价|购买|选择/.test(row.question||row.keyword))score+=3;if(row.brand_presence==='none')score+=2;if(row.competitor_risk==='high')score+=2;if(row.source_gap==='yes')score+=1;if(row.exact_url_hit==='yes')score-=2;if(score>=5)return'P0';if(score>=3)return'P1';if(score>=1)return'P2';return'P3';}
function nextAction(row){switch(row.status){case'planned':return'加入/创建 Scheduled Indexing 计划，完成 baseline 检测';case'baseline_done':return row.brand_presence==='none'||row.competitor_risk==='high'?'标记 need_content，优先生成内容':'观察并补充信源';case'need_content':return'用 geo-content-production 生成标题/文章，并进入上传发布';case'published':return'用 geo-indexing 检测 publishedUrl 是否 exact_url_hit';case'postpublish_monitoring':return'持续复测 answers/matrix，观察是否进入 stable';case'source_gap':return'用 geo-source-assets 找可控信源并补强';case'stable':return'保持维护，定期复测，防止 regression';case'regression':return'用 geo-analysis 复盘下降原因，补内容/信源';case'blocked':return'用 geo-troubleshooter 排查阻塞原因';default:return'人工复核下一步';}}
function mergeRows(existing,incoming){const map=new Map();for(const r of existing){const k=(r.question||r.keyword||'').toLowerCase();if(k)map.set(k,{...r});}for(const item of incoming){const k=(item.question||item.keyword||'').toLowerCase();const cur=map.get(k)||{keyword:item.keyword||keywordOf(item.question),question:item.question||item.keyword,priority:'',status:'planned',commercial_value:'unknown',brand_presence:'unknown',competitor_risk:'unknown',source_gap:'unknown',content_status:'not_started',published_url:'',exact_url_hit:'',weak_hit:'',last_evidence:'',source:'',next_action:'',notes:'',created_at:now(),updated_at:''};Object.assign(cur,Object.fromEntries(Object.entries(item).filter(([,v])=>v!==undefined&&v!=='')));cur.priority=cur.priority||scorePriority(cur);cur.next_action=nextAction(cur);cur.updated_at=now();map.set(k,cur);}return[...map.values()].sort((a,b)=>String(a.priority).localeCompare(String(b.priority))||String(a.status).localeCompare(String(b.status)));}
function renderMd(rows){const lines=['# GEO 关键词池','',`更新时间：${now()}`,'','| 优先级 | 状态 | 关键词/问题 | 品牌存在 | 竞品风险 | 信源缺口 | 下一步 |','|---|---|---|---|---|---|---|'];for(const r of rows)lines.push(`| ${r.priority||''} | ${r.status||''} | ${String(r.question||r.keyword).replace(/\|/g,'\\|')} | ${r.brand_presence||''} | ${r.competitor_risk||''} | ${r.source_gap||''} | ${String(r.next_action||'').replace(/\|/g,'\\|')} |`);return lines.join('\n');}
function renderActions(rows,top){const order={P0:0,P1:1,P2:2,P3:3};const arr=rows.filter(r=>r.status!=='stable').sort((a,b)=>(order[a.priority]??9)-(order[b.priority]??9)).slice(0,top);const lines=['# 关键词下一步动作','',`更新时间：${now()}`,''];for(const r of arr){lines.push(`## ${r.priority||''} · ${r.question||r.keyword}`);lines.push(`- 当前状态：${r.status}`);lines.push(`- 证据：${r.last_evidence||'(无)'}`);lines.push(`- 下一步：${r.next_action||nextAction(r)}`);lines.push('');}return lines.join('\n');}
function renderSummary(rows){const count=(field)=>rows.reduce((m,r)=>(m[r[field]||'unknown']=(m[r[field]||'unknown']||0)+1,m),{});return ['# 关键词池摘要','',`更新时间：${now()}`,'',`- 总数：${rows.length}`,'','## 优先级',...Object.entries(count('priority')).map(([k,v])=>`- ${k}: ${v}`),'','## 状态',...Object.entries(count('status')).map(([k,v])=>`- ${k}: ${v}`),''].join('\n');}
function writeAll(dir,rows,top=20){ensureDir(dir);writeCsv(poolFile(dir),rows);fs.writeFileSync(path.join(dir,'keyword_pool.md'),renderMd(rows),'utf8');fs.writeFileSync(path.join(dir,'keyword_next_actions.md'),renderActions(rows,top),'utf8');fs.writeFileSync(path.join(dir,'keyword_pool_summary.md'),renderSummary(rows),'utf8');return{csv:poolFile(dir),md:path.join(dir,'keyword_pool.md'),actions:path.join(dir,'keyword_next_actions.md'),summary:path.join(dir,'keyword_pool_summary.md')};}
function importAnswers(file,args){const brand=String(first(args,['brand','owned-brand','ownedBrand'],''));const ownedDomains=splitList(first(args,['owned-domains','ownedDomains'],''));const rows=unwrapRows(JSON.parse(fs.readFileSync(path.resolve(file),'utf8')));return rows.map(a=>{const q=a.topic||a.question||a.query||'';const content=String(a.content||'');const sites=Array.isArray(a.searchedSites)?a.searchedSites:[];const hasOwnedSite=sites.some(s=>s.articleIndexed||ownedDomains.some(d=>String(s.url||'').includes(d)));const mentionsBrand=brand&&content.includes(brand);const hasCompetitor=Array.isArray(a.competitors)&&a.competitors.length>0;let status='baseline_done';if(hasOwnedSite)status='stable';else if(mentionsBrand)status='source_gap';else status='need_content';return{question:q,keyword:keywordOf(q),status,brand_presence:mentionsBrand?'mentioned':'none',competitor_risk:hasCompetitor?'high':'unknown',source_gap:hasOwnedSite?'no':'yes',exact_url_hit:hasOwnedSite?'yes':'no',last_evidence:`answers:${a.platform||''}:${a.id||''}`,source:'answers',priority:''};}).filter(x=>x.question);}
function main(){const args=parseArgs(process.argv);if(args.help||args.h){usage();return;}const action=String(first(args,['action'],args._[0]||'summary'));const dir=outDir(args);const top=Number(first(args,['top'],20))||20;let rows=loadPool(dir);if(action==='init'){const files=writeAll(dir,rows,top);console.log(JSON.stringify({action,count:rows.length,files},null,2));return;}if(action==='import'){const file=first(args,['file']);if(!file)throw new Error('import 需要 --file');const source=String(first(args,['source'],path.basename(file)));const incoming=readQuestions(file).map(q=>({question:q,keyword:keywordOf(q),source,status:'planned'}));rows=mergeRows(rows,incoming);}else if(action==='import-answers'){const file=first(args,['answers-json','answersJson','file']);if(!file)throw new Error('import-answers 需要 --answers-json');rows=mergeRows(rows,importAnswers(file,args));}else if(action==='update'){const q=first(args,['question','keyword']);if(!q)throw new Error('update 需要 --question 或 --keyword');const item={question:q,keyword:keywordOf(q)};for(const f of FIELDS){const v=first(args,[f,f.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]);if(v!==undefined)item[f]=String(v);}if(item.status&&!STATES.has(item.status))throw new Error(`未知状态：${item.status}`);rows=mergeRows(rows,[item]);}else if(action==='next'||action==='summary'){}else throw new Error(`未知 action：${action}`);for(const r of rows){r.priority=r.priority||scorePriority(r);r.next_action=nextAction(r);}const files=writeAll(dir,rows,top);console.log(JSON.stringify({action,count:rows.length,files},null,2));}
main();
