#!/usr/bin/env node
// Best GEO CLI publication status checker.
const fs=require('fs'),path=require('path');
const {call}=require('../../geo-runtime/scripts/best_geo.js');
function arg(k){const i=process.argv.indexOf('--'+k);return i>=0?process.argv[i+1]:null}
function ids(k){return String(arg(k)||'').split(/[,，\s]+/).map(Number).filter(Boolean)}
function rows(r){const d=r?.data||r;return Array.isArray(d?.data)?d.data:Array.isArray(d?.list)?d.list:Array.isArray(d)?d:[]}
function csv(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
(async()=>{const articleIds=[...new Set([...ids('article-id'),...ids('article-ids')])],taskIds=[...new Set([...ids('task-id'),...ids('task-ids')])];const q={page:Number(arg('page')||1),limit:Number(arg('limit')||200)};if(arg('company-id'))q.companyId=Number(arg('company-id'));if(arg('product-id'))q.productId=Number(arg('product-id'));if(arg('dry-run')){console.log(JSON.stringify({dryRun:true,capabilities:['publicationTasks.list','publicationRecords.list'],query:q},null,2));return}const tasks=rows(await call('publicationTasks.list',q)),records=rows(await call('publicationRecords.list',q));const wanted=[...articleIds,...taskIds];const match=x=>!wanted.length||wanted.some(id=>[x.id,x.taskId,x.articleId,x.publicationId].map(Number).includes(id));const out=records.filter(match).map(x=>({...x,statusLabel:x.statusLabel||x.status,publishedUrl:x.publishedUrl||''}));const dir=path.resolve(arg('output-dir')||path.join(arg('project-dir')||'.','06_发布记录','发布状态回查'));fs.mkdirSync(dir,{recursive:true});const stamp=new Date().toISOString().slice(0,10);const files={json:path.join(dir,`publication_status_${stamp}.json`),csv:path.join(dir,`publication_status_${stamp}.csv`)};fs.writeFileSync(files.json,JSON.stringify({tasks:tasks.filter(match),records:out,query:q},null,2));const fields=['articleId','publicationId','taskId','platform','statusLabel','publishedUrl'];fs.writeFileSync(files.csv,[fields.join(','),...out.map(x=>fields.map(f=>csv(x[f])).join(','))].join('\n')+'\n');console.log(JSON.stringify({action:'publication-status',taskCount:tasks.length,recordCount:out.length,readyUrls:out.filter(x=>x.publishedUrl).length,files},null,2));})().catch(e=>{console.error(e.message||e);process.exit(1)});
