#!/usr/bin/env node
// Best GEO CLI material uploader. Authentication is owned by best-geo.
const fs=require('fs'),path=require('path');
const {plan,apply,call}=require('../../geo-runtime/scripts/best_geo.js');
function vals(k){const out=[];for(let i=2;i<process.argv.length;i++)if(process.argv[i]==='--'+k&&process.argv[i+1])out.push(process.argv[i+1]);return out}
function arg(k){const i=process.argv.indexOf('--'+k);return i>=0?process.argv[i+1]:null}
function has(k){return process.argv.includes('--'+k)}
function list(v){return String(v||'').split(/[,，|]/).map(x=>x.trim()).filter(Boolean)}
function ext(f){return path.extname(f).toLowerCase()}
function urlOf(x){return x?.url||x?.imageUrl||x?.videoUrl||x?.resourceUrl||x?.ossUrl||x?.fileUrl||x?.data?.url||x?.data?.resourceUrl||''}
(async()=>{const files=[...vals('file'),...vals('files')];if(!files.length)throw Error('请使用 --file 图片或视频路径；支持重复传入 --file。');const productId=Number(arg('product-id')||0),companyId=Number(arg('company-id')||0),tags=list(arg('tags'));const results=[];for(const file of files){if(!fs.existsSync(file))throw Error(`文件不存在：${file}`);const e=ext(file);let capability,input;if(['.png','.jpg','.jpeg'].includes(e)){capability='images.create';input={filePath:path.resolve(file),name:arg('name')||path.basename(file,path.extname(file)),tags};if(productId)input.productId=productId;else if(companyId)input.companyId=companyId;else throw Error('图片上传需要 --product-id 或 --company-id');}else if(e==='.mp4'){const thumbnail=arg('thumbnail');if(!thumbnail)throw Error('视频上传需要 --thumbnail 和 --duration');if(!fs.existsSync(thumbnail))throw Error(`缩略图不存在：${thumbnail}`);const duration=Number(arg('duration')||0);if(!duration)throw Error('视频上传需要有效的 --duration（秒）');capability='videos.create';input={videoPath:path.resolve(file),thumbnailPath:path.resolve(thumbnail),duration,title:arg('title')||path.basename(file,e),tags};if(productId)input.productId=productId;else if(companyId)input.companyId=companyId;else throw Error('视频上传需要 --product-id 或 --company-id');}else throw Error(`不支持的素材格式：${e}`);if(has('dry-run')){results.push({dryRun:true,capability,input});continue}if(!has('force'))throw Error('素材上传会产生平台写入/费用，请先 --dry-run，确认后加 --force。');const p=await plan(capability,input);const pid=p?.data?.planId||p?.planId;if(!pid)throw Error('CLI 未返回 planId');const created=await apply(pid);const d=created?.data||created;const id=Number(d?.id||d?.materialId||d?.imageId||d?.videoId||0);let detail=d;if(id)detail=await call(capability.replace('.create','.get'),{id});results.push({file,capability,id,created:d,detail,url:urlOf(detail)||urlOf(d)});}console.log(JSON.stringify({count:results.length,results},null,2));})().catch(e=>{console.error(e.message||e);process.exit(1)});
