#!/usr/bin/env node
const { loadGeoConfig, headers: geoHeaders, mask } = require('../../geo-runtime/scripts/credentials.js');
const { unwrapRows } = require('../../geo-runtime/scripts/json_helpers.js');

function parseArgs(argv){const out={_:[]};for(let i=2;i<argv.length;i++){const token=argv[i];if(!token.startsWith('--')){out._.push(token);continue;}const raw=token.slice(2);const eq=raw.indexOf('=');const key=eq>=0?raw.slice(0,eq):raw;const value=eq>=0?raw.slice(eq+1):(!argv[i+1]||argv[i+1].startsWith('--')?true:argv[++i]);out[key]=value;}return out;}
function first(args,names,fallback){for(const n of names)if(args[n]!==undefined&&args[n]!=='')return args[n];return fallback;}
function splitList(v){return String(v||'').split(/[,，|\n]/).map(x=>x.trim()).filter(Boolean);}
function bool(v){if(v===undefined)return undefined;return ['1','true','yes','是'].includes(String(v).toLowerCase());}
function cfgChecked(){const cfg=loadGeoConfig();if(!cfg.geo.openKey)throw new Error('未配置 GEO openKey。');if(!Number(cfg.defaults.companyId))throw new Error('未设置默认 companyId，请先使用 geo-config。');return cfg;}
function usage(){console.log(`Usage:
  node geo-media-submission/scripts/media_submission.js --action list [--taxonomy 财经商业] [--area 上海] [--ai-included 豆包]
  node geo-media-submission/scripts/media_submission.js --action enums
  node geo-media-submission/scripts/media_submission.js --action submit --article-ids 1,2 --media-ids 10,11 [--force]
  node geo-media-submission/scripts/media_submission.js --action records [--article-id 1]`);}
function relative(endpoint,query){const qs=new URLSearchParams();for(const[k,v]of Object.entries(query||{})){if(v===undefined||v===null||v===''||(Array.isArray(v)&&!v.length))continue;for(const item of(Array.isArray(v)?v:[v]))qs.append(k,String(item));}return endpoint+(qs.toString()?`?${qs}`:'');}
async function request(cfg,method,endpoint,{query={},body}={}){const rel=relative(endpoint,query);const headers={...geoHeaders(cfg),Accept:'application/json'};if(body!==undefined)headers['Content-Type']='application/json; charset=utf-8';const res=await fetch(String(cfg.geo.baseUrl).replace(/\/$/,'')+rel,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});const text=await res.text();let data;try{data=JSON.parse(text);}catch{data=text;}if(!res.ok||(data&&typeof data==='object'&&data.statusCode!==undefined&&data.statusCode!==0)){const msg=data&&typeof data==='object'?(data.message||data.msg||JSON.stringify(data).slice(0,500)):String(data).slice(0,500);throw new Error(`${method} ${endpoint} 失败：HTTP ${res.status}；${msg}`);}return{data,request:{method,path:rel,openKey:mask(cfg.geo.openKey)}};}
function mediaView(x){return{id:x.id,mediaName:x.mediaName,price:Number(x.price||0),withLink:Boolean(x.withLink),caseUrl:x.caseUrl||'',area:x.area||'',platform:x.platform||'',taxonomy:x.taxonomy||'',titleLimit:x.titleLimit||0,mediaType:x.mediaType,aiIncluded:x.aiIncluded||[],remark:x.remark||'',successRadio:x.successRadio,isFavorite:Boolean(x.isFavorite)};}
function listQuery(args){return{page:first(args,['page'],1),limit:first(args,['limit'],30),id:first(args,['id'],undefined),mediaName:first(args,['media-name','mediaName'],undefined),taxonomy:splitList(first(args,['taxonomy'],'')),area:splitList(first(args,['area'],'')),platform:splitList(first(args,['platform'],'')),remark:first(args,['remark'],undefined),withLink:bool(first(args,['with-link','withLink'],undefined)),aiIncluded:splitList(first(args,['ai-included','aiIncluded'],'')),onlyFavorite:bool(first(args,['only-favorite','onlyFavorite'],undefined))};}
async function listAction(cfg,args){const res=await request(cfg,'GET','/v1/publication-media',{query:listQuery(args)});let rows=unwrapRows(res.data).map(mediaView);const max=Number(first(args,['max-price','maxPrice'],0));const min=Number(first(args,['min-price','minPrice'],0));if(max)rows=rows.filter(x=>x.price<=max);if(min)rows=rows.filter(x=>x.price>=min);console.log(JSON.stringify({rows,request:res.request},null,2));}
async function enumsAction(cfg){const res=await request(cfg,'GET','/v1/publication-media/query-enums');console.log(JSON.stringify({enums:res.data?.data||res.data,request:res.request},null,2));}
async function getMedia(cfg,id){const res=await request(cfg,'GET','/v1/publication-media',{query:{page:1,limit:10,id}});return unwrapRows(res.data).map(mediaView).find(x=>Number(x.id)===Number(id));}
async function recordsAction(cfg,args){const query={page:first(args,['page'],1),limit:first(args,['limit'],50),companyId:cfg.defaults.companyId,articleId:first(args,['article-id','articleId'],undefined),mediaId:first(args,['media-id','mediaId'],undefined),status:first(args,['status'],undefined)};const res=await request(cfg,'GET','/v1/publication-media/publish',{query});const rows=unwrapRows(res.data).map(x=>({id:x.id,articleId:x.article?.id||x.articleId,articleTitle:x.article?.title||'',mediaId:x.media?.id||x.mediaId,mediaName:x.media?.mediaName||'',status:x.status,publishedUrl:x.publishedUrl||'',publishedAt:x.publishedAt||'',failReason:x.failReason||'',createdAt:x.createdAt}));console.log(JSON.stringify({rows,request:res.request},null,2));}
async function submitAction(cfg,args){const articleIds=splitList(first(args,['article-ids','articleIds','article-id','articleId'],'')).map(Number).filter(Boolean);const mediaIds=splitList(first(args,['media-ids','mediaIds','media-id','mediaId'],'')).map(Number).filter(Boolean);if(!articleIds.length||!mediaIds.length)throw new Error('submit 需要 articleIds 和 mediaIds。');if(articleIds.length>20)throw new Error('一次最多20篇文章。');if(mediaIds.length>50)throw new Error('一次最多50个媒体。');const media=(await Promise.all(mediaIds.map(id=>getMedia(cfg,id)))).filter(Boolean);if(media.length!==mediaIds.length)throw new Error('部分媒体ID不存在或无权访问，请重新查询媒体列表。');const combinationCount=articleIds.length*mediaIds.length;const estimatedTotal=articleIds.length*media.reduce((sum,x)=>sum+x.price,0);const preview={dryRun:!args.force,articleIds,media:media.map(mediaView),combinationCount,estimatedTotal,warning:'aiIncluded是媒体库标签，不保证客户监测中的AI实际引用。'};if(!args.force){console.log(JSON.stringify(preview,null,2));return;}const single=articleIds.length===1&&mediaIds.length===1;const endpoint=single?'/v1/publication-media/publish':'/v1/publication-media/publish/batch';const body=single?{articleId:articleIds[0],mediaId:mediaIds[0]}:{articleIds,mediaIds};const submitted=await request(cfg,'POST',endpoint,{body});const checks=[];for(const articleId of articleIds){const verify=await request(cfg,'GET','/v1/publication-media/publish',{query:{page:1,limit:100,companyId:cfg.defaults.companyId,articleId}});checks.push(...unwrapRows(verify.data).filter(x=>mediaIds.includes(Number(x.media?.id||x.mediaId))).map(x=>({id:x.id,articleId,mediaId:x.media?.id||x.mediaId,mediaName:x.media?.mediaName||'',status:x.status,publishedUrl:x.publishedUrl||'',failReason:x.failReason||''})));}console.log(JSON.stringify({ok:true,submitted:submitted.data?.data||submitted.data,verification:checks},null,2));}
async function main(){const args=parseArgs(process.argv);if(args.help||args.h){usage();return;}const action=String(first(args,['action'],args._[0]||'list'));const cfg=cfgChecked();if(action==='list')return listAction(cfg,args);if(action==='enums')return enumsAction(cfg);if(action==='records')return recordsAction(cfg,args);if(action==='submit')return submitAction(cfg,args);throw new Error(`未知 action：${action}`);}
main().catch(e=>{console.error(e.message||e);process.exit(1);});
