#!/usr/bin/env node
const { call, plan, apply } = require('../../geo-runtime/scripts/best_geo.js');
const { unwrapRows } = require('../../geo-runtime/scripts/json_helpers.js');

function parseArgs(argv){const out={_:[]};for(let i=2;i<argv.length;i++){const token=argv[i];if(!token.startsWith('--')){out._.push(token);continue;}const raw=token.slice(2);const eq=raw.indexOf('=');const key=eq>=0?raw.slice(0,eq):raw;const value=eq>=0?raw.slice(eq+1):(!argv[i+1]||argv[i+1].startsWith('--')?true:argv[++i]);out[key]=value;}return out;}
function first(args,names,fallback){for(const n of names)if(args[n]!==undefined&&args[n]!=='')return args[n];return fallback;}
function splitList(v){return String(v||'').split(/[,，|\n]/).map(x=>x.trim()).filter(Boolean);}
function bool(v){if(v===undefined)return undefined;return ['1','true','yes','是'].includes(String(v).toLowerCase());}
function cfgChecked(){const i=process.argv.indexOf('--company-id');return {defaults:{companyId:i>=0?Number(process.argv[i+1]||0):0}};}
function usage(){console.log(`Usage:
  node geo-media-submission/scripts/media_submission.js --action list [--taxonomy 财经商业] [--area 上海] [--ai-included 豆包]
  node geo-media-submission/scripts/media_submission.js --action enums
  node geo-media-submission/scripts/media_submission.js --action submit --article-ids 1,2 --media-ids 10,11 [--force]
  node geo-media-submission/scripts/media_submission.js --action records [--article-id 1]`);}
function relative(endpoint,query){const qs=new URLSearchParams();for(const[k,v]of Object.entries(query||{})){if(v===undefined||v===null||v===''||(Array.isArray(v)&&!v.length))continue;for(const item of(Array.isArray(v)?v:[v]))qs.append(k,String(item));}return endpoint+(qs.toString()?`?${qs}`:'');}
async function request(cfg,capability,input,{write=false}={}){
  const data=write?await (async()=>{const p=await plan(capability,input);const id=p?.data?.planId||p?.planId;if(!id)throw Error('CLI 未返回 planId');return apply(id)})():call(capability,input);
  return {data,request:{capability}};
}
function mediaView(x){return{id:x.id,mediaName:x.mediaName,price:Number(x.price||0),withLink:Boolean(x.withLink),caseUrl:x.caseUrl||'',area:x.area||'',platform:x.platform||'',taxonomy:x.taxonomy||'',titleLimit:x.titleLimit||0,mediaType:x.mediaType,aiIncluded:x.aiIncluded||[],remark:x.remark||'',successRadio:x.successRadio,isFavorite:Boolean(x.isFavorite)};}
function listQuery(args){return{page:Number(first(args,['page'],1)),limit:Number(first(args,['limit'],30)),mediaName:first(args,['media-name','mediaName'],undefined)};}
async function listAction(cfg,args){const res=await request(cfg,'mediaPlatforms.list',listQuery(args));let rows=unwrapRows(res.data).map(mediaView);const max=Number(first(args,['max-price','maxPrice'],0));const min=Number(first(args,['min-price','minPrice'],0));if(max)rows=rows.filter(x=>x.price<=max);if(min)rows=rows.filter(x=>x.price>=min);console.log(JSON.stringify({rows,request:res.request},null,2));}
async function enumsAction(){throw new Error('Best GEO CLI 暂不提供媒体枚举接口；请使用 mediaPlatforms.list 并按返回字段筛选。');}
async function getMedia(cfg,id){const data=await call('mediaPlatforms.get',{mediaId:Number(id)});return mediaView(data?.data?.data||data?.data||data);}
async function recordsAction(cfg,args){const query={page:Number(first(args,['page'],1)),limit:Number(first(args,['limit'],50)),companyId:cfg.defaults.companyId||undefined,articleId:first(args,['article-id','articleId'],undefined),mediaId:first(args,['media-id','mediaId'],undefined)};const res=await request(cfg,'mediaPublications.list',query);const rows=unwrapRows(res.data).map(x=>({id:x.id,articleId:x.article?.id||x.articleId,articleTitle:x.article?.title||'',mediaId:x.media?.id||x.mediaId,mediaName:x.media?.mediaName||'',status:x.status,publishedUrl:x.publishedUrl||'',publishedAt:x.publishedAt||'',failReason:x.failReason||'',createdAt:x.createdAt}));console.log(JSON.stringify({rows,request:res.request},null,2));}
async function submitAction(cfg,args){const articleIds=splitList(first(args,['article-ids','articleIds','article-id','articleId'],'')).map(Number).filter(Boolean);const mediaIds=splitList(first(args,['media-ids','mediaIds','media-id','mediaId'],'')).map(Number).filter(Boolean);if(!articleIds.length||!mediaIds.length)throw new Error('submit 需要 articleIds 和 mediaIds。');if(articleIds.length>20)throw new Error('一次最多20篇文章。');if(mediaIds.length>20)throw new Error('一次最多20个媒体（CLI 限制）。');const media=(await Promise.all(mediaIds.map(id=>getMedia(cfg,id)))).filter(Boolean);if(media.length!==mediaIds.length)throw new Error('部分媒体ID不存在或无权访问，请重新查询媒体列表。');const combinationCount=articleIds.length*mediaIds.length;const estimatedTotal=articleIds.length*media.reduce((sum,x)=>sum+x.price,0);const preview={dryRun:!args.force,articleIds,media:media.map(mediaView),combinationCount,estimatedTotal,warning:'aiIncluded是媒体库标签，不保证客户监测中的AI实际引用。'};if(!args.force){console.log(JSON.stringify(preview,null,2));return;}const submitted=[];for(const articleId of articleIds){const capability=mediaIds.length===1?'mediaPublications.create':'mediaPublications.batchCreate';const body=mediaIds.length===1?{articleId,mediaId:mediaIds[0]}:{articleId,mediaIds};submitted.push(await request(cfg,capability,body,{write:true}));}const checks=[];for(const articleId of articleIds){const verify=await request(cfg,'mediaPublications.list',{page:1,limit:100,companyId:cfg.defaults.companyId,articleId});checks.push(...unwrapRows(verify.data).filter(x=>mediaIds.includes(Number(x.media?.id||x.mediaId))).map(x=>({id:x.id,articleId,mediaId:x.media?.id||x.mediaId,mediaName:x.media?.mediaName||'',status:x.status,publishedUrl:x.publishedUrl||'',failReason:x.failReason||''})));}console.log(JSON.stringify({ok:true,submitted:submitted.map(x=>x.data?.data||x.data),verification:checks},null,2));}
async function main(){const args=parseArgs(process.argv);if(args.help||args.h){usage();return;}const action=String(first(args,['action'],args._[0]||'list'));const cfg=cfgChecked();if(action==='list')return listAction(cfg,args);if(action==='enums')return enumsAction(cfg);if(action==='records')return recordsAction(cfg,args);if(action==='submit')return submitAction(cfg,args);throw new Error(`未知 action：${action}`);}
main().catch(e=>{console.error(e.message||e);process.exit(1);});
